### ISSUE TITLE
Launch with workspace resolution

### ISSUE THREAD

**Issue by attiand** [jbosstools/jbosstools-quarkus#118]
I have created the simplest possible Maven Quarkus project and it launches from within the Eclipse IDE without problem. I now create a second maven-jar project in the Eclipse workspace and add a dependency from the Quarkus project to my jar project.

I have Maven workspace resolution enabled and everything seems ok, Eclipse has resolved the dependency, i.e. the dependency appears in the Quarkus project under *Maven dependencies* and any code I write in the Quarkus project compiles against my dependency. 

Now if I launch my Quarkus application with the *Quarkus application* launch configuration I get an error:

```
Could not resolve dependencies for project org.acme:code-with-quarkus:jar:1.0.0-SNAPSHOT: Could not find artifact test:dep:jar:0.0.1-SNAPSHOT
```

If I run a `mvn install` on the dependency Maven project it works as it should.

It seems like the Quarkus application launch configuration simply launches the maven binary and let Maven deal with dependency resolution. This is however this is not what the user expect as the dependency seems resolved in the workspace.

**Comment by jeffmaury** [comment]
Fixed by d0dde8ef197218f2d1157db8d11c67626a2a547e
