### ISSUE TITLE
Support for system-wide Maven in Eclipse

### ISSUE THREAD

**Issue by rob-spoor** [jbosstools/jbosstools-quarkus#130]
We have an existing Quarkus project where we've removed the `mvnw` scripts in favour of the system's Maven installation. However, this causes an error when creating Run / Debug launch configurations in Eclipse:

    java.lang.NullPointerException: Cannot invoke "org.eclipse.core.runtime.IPath.toOSString()" because the return value of "org.jboss.tools.quarkus.tool.ToolSupport.getScriptPath()" is null

After restoring the `mvnw` scripts this works again. However, it would be nice that if the `mvnw` scripts don't exist, the system installation would be used as default. This could be done in a few ways:
* Link to Eclipse's internal Maven
* Search the system path for `mvn` / `mvn.cmd`
* Let the user specify the Maven executable

IntelliJ uses an option of the first and third option - let the user specify the Maven executable, defaulting to the internal Maven.

**Comment by jeffmaury** [comment]
Fixed by d0dde8ef197218f2d1157db8d11c67626a2a547e
