### ISSUE TITLE
Marketplace installation refers to missing repository URL

### ISSUE THREAD

**Issue by nitind** [jbosstools/jbosstools-quarkus#142]
While attempting to install https://marketplace.eclipse.org/content/quarkus-tools, quite a number of these get emitted:

org.eclipse.equinox.p2.core.ProvisionException: No repository found at https://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/4.18.0.Final-SNAPSHOT/REPO/.

**Comment by sbouchet** [comment]
Hi @nitind, thanks for reporting this. we'll be fixing it for the next release, via https://issues.redhat.com/browse/JBIDE-27801
