### ISSUE TITLE
Unsupported or unrecognized ssl message

### ISSUE THREAD

**Issue by pestapever** [jbosstools/jbosstools-quarkus#149]
I get this error after completing the process of creating a Quarkus project using the extension on Eclipse. I think it is due to the corporate proxies, since the error is received only on the corporate desktop.
<img width="305" alt="Cattura" src="https://user-images.githubusercontent.com/20123656/124482195-53331400-dda9-11eb-8184-c9d12f965e1d.PNG">

**Comment by pestapever** [comment]
I have already tried starting Eclipse with proxy environment variables but without success

**Comment by jeffmaury** [comment]
What kind of proxies are you using ? it's possible that we don't configure properly when reaching code.quarkus.io

**Comment by pestapever** [comment]
Http proxies

**Comment by jeffmaury** [comment]
Can yoyu share your proxy configuration in Eclipse ?

**Comment by pestapever** [comment]
Resolved

**Comment by pestapever** [comment]
Resolved

**Comment by pestapever** [comment]
Resolved
