### ISSUE TITLE
Quarkus plugin messes with organize imports on MacOS

### ISSUE THREAD

**Issue by oole** [jbosstools/jbosstools-quarkus#179]
After switching to Eclipse 2022-03, organize imports is misbehaving. The ordering for projects and global setting is no longer respected.

With a defined order of:

java
javax
org
com

the order ends up being

java
javax
com
org

I could not explain why my settings wouldn't stick. So I re-installed Eclipse (JaveEE edition), and went through all plugins individually, and the Quarkus Tools are definitively causing the issue.

Quarkus Tools: 1.6.0.v20220323-1610
Eclipse: Version: 2022-03 (4.23.0)
OS: MacOS 12.4

----------------------------------------
**Steps to reproduce**:
1. Install clean Eclipse JaveEE edition
2. Install Quarkus Tools
3. Organize imports

**Expected**: Organize imports should respect defined order (default of java, javax, org, com)

**Actual**: Organize imports results in ordering java, javax, com, org

**Comment by oole** [comment]
Another find, now that eclipse 2022-06 released. I wanted to update eclipse, but all update sites vanished. After uninstalling the quarkus tools and a restart the updates sites show up again. It seems that the quarkus tools are causing this issue as well.

**Comment by morhei** [comment]
Same issue on Linux Mint and Eclipse 2022-06

**Comment by jeffmaury** [comment]
This issue is related to embedding JDT-LS, issue is being tracked here: https://issues.redhat.com/browse/JBIDE-28504

**Comment by oole** [comment]
Thanks for clarifying!

**Comment by jeffmaury** [comment]
Fixed by af405dfe94b6ef488b8c73fa08ff33301dea0e6b
