### ISSUE TITLE
Installing the Quarkus Tools makes the IDE unusable

### ISSUE THREAD

**Issue by heike2718** [jbosstools/jbosstools-quarkus#190]
After installing the Quarkus tools to a fresh copy of latest Eclipse version, the IDE can no longer be used properly. The following things no longer work correctly (minimal set of broken things):

- Configuration of the default editor for *.properties files permanently ignored (always generic editor is chosen by double click)
- Configuration Preferences -> Java -> Code Sytyle -> code template (no templates for Comments)
- Generate getters/setters returns incorrect result
- autocomplete can no longer be configured properly

**Version-Info:**

Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2022-06 (4.24.0)
Build id: 20220609-1112
OS: Linux, v.4.19.0-21-amd64, x86_64 / gtk 3.24.5
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.3+7
Java version: 17.0.3

**Reproduce the Behavior**

Install a fresh copy of eclipse-jee-2022-06-R-linux-gtk-x86_64.tar.gz and check, that all configured settings work as expected.

Install the Quarkus tools => The settings break and the IDE can no longer be used for development at the usual speed.

**Comment by jeffmaury** [comment]
Fixed by af405dfe94b6ef488b8c73fa08ff33301dea0e6b
