### ISSUE TITLE
The installation cannot be completed as requested. [eclipse-jee-2022-09-R-win32-x86_64][Quarkus Tools 4.24.0.Final]

### ISSUE THREAD

**Issue by fugerit79** [jbosstools/jbosstools-quarkus#192]
I tried to install Quarkus Tools 4.24.0.Final on the new eclipse-jee-2022-09-R-win32-x86_64.

But i get the error : "The installation cannot be completed as requested"

The complete error message is (Any idea on how to fix it?, thanks in advance)

Cannot complete the install because of a conflicting dependency.
  Software being installed: Quarkus Tools 1.7.0.v20220622-0658 (org.jboss.tools.quarkus.feature.feature.group 1.7.0.v20220622-0658)
  Software currently installed: M2E - Maven Integration for Eclipse 2.0.4.20220904-1703 (org.eclipse.m2e.feature.feature.group 2.0.4.20220904-1703)
  Only one of the following can be installed at once: 
    M2E Maven Integration for Eclipse Core 2.0.3.20220904-1703 (org.eclipse.m2e.core 2.0.3.20220904-1703)
    M2E Maven Integration for Eclipse Core 1.18.4.20220208-0831 (org.eclipse.m2e.core 1.18.4.20220208-0831)
  Cannot satisfy dependency:
    From: JDT MicroProfile Extension 0.4.0.20220324-1655 (org.eclipse.lsp4mp.jdt.core 0.4.0.20220324-1655)
    To: osgi.bundle; org.eclipse.m2e.lifecyclemapping.defaults 0.0.0
  Cannot satisfy dependency:
    From: M2E - Maven Integration for Eclipse 2.0.4.20220904-1703 (org.eclipse.m2e.feature.feature.group 2.0.4.20220904-1703)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.core [2.0.3.20220904-1703,2.0.3.20220904-1703]
  Cannot satisfy dependency:
    From: Default Build Lifecycle Mapping Metadata 1.17.1.20210115-1536 (org.eclipse.m2e.lifecyclemapping.defaults 1.17.1.20210115-1536)
    To: osgi.bundle; org.eclipse.m2e.core [1.16.0,2.0.0)
  Cannot satisfy dependency:
    From: Quarkus Tools 1.7.0.v20220622-0658 (org.jboss.tools.quarkus.feature.feature.group 1.7.0.v20220622-0658)
    To: org.eclipse.equinox.p2.iu; org.eclipse.lsp4mp.jdt.core 0.0.0

**Comment by jeffmaury** [comment]
4.24.0 is not compatible with 2022-09 as M2E add incompatible changes. We are preparing 4.25.0 to be released soon that will be compatible with 2022-09

**Comment by fugerit79** [comment]
OK thank you very much.
