### ISSUE TITLE
Visual Route Editor for the Quarkus runtime

### ISSUE THREAD

**Issue by bvahdat** [jbosstools/jbosstools-quarkus#198]
My apologizes beforehand if this is the wrong place to ask.

Is the Visual Route Editor for Camel documented below is available for the Quarkus runtime as well, or only Spring-Boot?

https://tools.jboss.org/features/fusetools.html

**Comment by jeffmaury** [comment]
@apupier can you help ?

**Comment by apupier** [comment]
It is available only for Camel 2.x with Camel XML DSL.
So not Camel Quarkus extension which requires Camel 3

For Camel 3.x, there is [Kaoto](https://github.com/KaotoIO/ ) project which is providing vizualiation for Camel Yaml DSL and thanks to its architecture should be possible to leverage in Eclipse IDE, and so Jboss Tools if there is enough interest for it.

**Comment by bvahdat** [comment]
Thanks @apupier.

So do I see it right that as per today, having Java-DSL in Quarkus runtime there is no tooling out there to visualize my Camel routing, right?

**Comment by apupier** [comment]
At design time, there is no tooling to visualize Camel Java-DSL routes.
At runtime, for Quarkus in JVM mode, you should be able to use hawt.io.

**Comment by bvahdat** [comment]
Thanks for the clarification.
