### ISSUE TITLE
Run configuration fails for multi-module setup

### ISSUE THREAD

**Issue by famod** [jbosstools/jbosstools-quarkus#56]
I am seeing the following error:
![image](https://user-images.githubusercontent.com/22860528/73552858-46d6b900-4449-11ea-9ca2-c1f2698dbeb6.png)
when trying to run Quarkus via Quarkus Launch Configuration for the `dist` module of following project: https://github.com/famod/modmono-quarkus

There is _no_ problem running the `getting-started` project.

Quarkus Eclipse Feature: `0.0.1.v20200130-1632`

**Comment by jeffmaury** [comment]
Replicated on https://issues.redhat.com/browse/JBIDE-27058

**Comment by famod** [comment]
So should reporters generally create jira issues instead of github issues?

**Comment by jeffmaury** [comment]
Yes JIRA is the JBoss Tools bug repository

**Comment by famod** [comment]
Fix confirmed in 4.15.0, thanks!

PS: Reported somthing else: https://issues.redhat.com/browse/JBIDE-27283
