### ISSUE TITLE
Add possibility to select active profile when quarkus:dev is starting

### ISSUE THREAD

**Issue by andrzejszywala** [jbosstools/jbosstools-quarkus#92]
It would be nice to have possibility to select active profile from the workbench "Run configurations" dialog. For example if I have in application.properties file `quarkus.datasource.jdbc.url=jdbc:oracle:thin:@mydb:1521/service
%mydb1.quarkus.datasource.jdbc.url=jdbc:oracle:thin:@mydb1:1521/service1
%mydb2.quarkus.datasource.jdbc.url=jdbc:oracle:thin:@mydb2:1521/service2`
then in "Run configurations" it could be list with available profiles. Then after clicking on the Run button -Dquarkus.profile property will be added to the Quarkus application. Something like on attached image.
 
![quarkus_profile](https://user-images.githubusercontent.com/10794859/82118664-0b05fc00-9779-11ea-912b-f194820e2c25.png)

**Comment by jeffmaury** [comment]
That's a good idea. As JIRA is where we track our activivity, I replaced it here: https://issues.redhat.com/browse/JBIDE-27277
