### ISSUE TITLE
Stack trace in console

### ISSUE THREAD

**Issue by akondasif** [jbosstools/jbosstools-quarkus#99]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, stack traces due to exception handling should not be printed. See https://cwe.mitre.org/

Source: https://github.com/jbosstools/jbosstools-quarkus/blob/master/tests/org.jboss.tools.quarkus.core.test/projects/maven/code-with-quarkus-maven/.mvn/wrapper/MavenWrapperDownloader.java

Fix: https://github.com/jbosstools/jbosstools-quarkus/pull/98

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by jeffmaury** [comment]
This is part of a test project generated by code.quarkus.io and is also the core part of Maven wrapper and user is not expected to modify code. You should report to the Maven wrapper project
